// import devaimage from "../../../public/images/deva.png";
export const mentorsData = [
  {
    _id: "6996e3571df3a4b0ea1c826c",
    name: "Devaraju Polasi",
    role: "Lead – AEM Developer",
    image:
      //   "https://lnywvafdnrevojhgqfbt.supabase.co/storage/v1/object/public/mentors/1771496277824_deva.png",
      "/images/deva.png",
    shortStory:
      "Growing with CJSS by building scalable and reliable AEM backend solutions.",
    fullStory:
      '"My journey at CJSS Technologies has been one of growth, learning, and long-term commitment. Being part of the organization from its early stages, I have had the unique opportunity to grow alongside the company and contribute to its evolution over the years.\\n\\nWhen I joined CJSS Technologies, the focus was on building strong foundations. As an AEM Backend Developer, my early responsibilities involved understanding the platform deeply and delivering reliable backend solutions using Adobe Experience Manager. Working on core AEM concepts such as OSGi services, Sling Models, workflows, schedulers, and integrations gave me a solid technical base and a clear understanding of enterprise-level content management systems.\\n\\nAs the company expanded, so did the scale and complexity of the projects. With that growth came greater responsibility. My role evolved from executing individual tasks to owning backend components, contributing to design decisions, and ensuring that implementations followed best practices. I became more involved in reviewing code, supporting deployments, troubleshooting production issues, and helping maintain stable and scalable AEM platforms.\\n\\nOver time, I also grew professionally in how I collaborated across teams. Working closely with frontend developers, QA, DevOps, and stakeholders helped me understand the complete delivery lifecycle. This exposure strengthened my ability to think beyond isolated features and focus on system reliability, performance, and long-term maintainability.\\n\\nWhat truly defines my experience at CJSS Technologies is the work culture. The organization promotes trust, ownership, and open communication. Developers are encouraged to ask questions, share ideas, and continuously improve. The leadership provides guidance while also allowing the freedom to take responsibility, which has played a key role in my technical and professional growth.\\n\\nToday, I continue to work as an AEM Backend Developer at CJSS Technologies, contributing to enterprise solutions that support both internal platforms and client deliveries. My focus is on building clean backend architectures, ensuring quality and consistency, and supporting the team with the experience I’ve gained over the years.\\n\\nLooking back, CJSS Technologies has been more than just a place of work for me—it has been a space where my skills, confidence, and mindset have evolved naturally. Growing with the company from its early days to where it stands today has been deeply rewarding, and it is a journey I am proud to be part of and continue forward.",\r\n',
    yearsAtCompany: "5+ years",
    achievements: [
      "AEM Backend Architecture",
      "Platform Stability & Scalability",
      "Code Quality & Best Practices",
    ],
    quote: "Growth comes from building, learning, and evolving together.",
    createdAt: "2026-02-19T10:17:59.265Z",
    updatedAt: "2026-02-19T10:19:53.962Z",
    __v: 0,
  },
  {
    _id: "6995acbcf0671e2b2691a3a3",
    name: "Chaitanya",
    role: "Lead – Frontend",
    image: "/images/chaitanya.png",
    //   "https://lnywvafdnrevojhgqfbt.supabase.co/storage/v1/object/public/mentors/1771495472775_chaitanya.png",
    shortStory: "Delivering clear and scalable user experiences.",
    fullStory:
      "Great user experiences start with clarity, and that’s been the focus of my journey at CJSS Technologies.\\n\\nLeading the frontend team means thinking beyond screens and components. It’s about how users interact with platforms, how performance feels at scale, and how frontend architecture supports long-term growth. From early on, I’ve worked closely with teams to build interfaces that are intuitive, consistent, and reliable.\\n\\nWhat stands out at CJSS is the way frontend development is treated as a core part of delivery, not an afterthought. I’ve had the opportunity to guide teams on design systems, performance optimization, and best practices while staying hands-on with modern frontend technologies.\\n\\nAs the team grew, my role evolved into leading frontend delivery across projects. That includes mentoring developers, aligning frontend work with backend and platform teams, and ensuring quality across different user-facing applications.\\n\\nToday, I lead the Frontend team at CJSS Technologies, supporting the delivery of scalable and high-performing user interfaces across enterprise platforms. Collaboration is central to how we work — with designers, backend teams, and stakeholders — to ensure smooth and consistent user experiences.\\n\\nCJSS Technologies has created an environment where frontend engineers can grow, take ownership, and contribute meaningfully. Being part of this journey has been both challenging and rewarding, and it continues to push me to improve every day.",
    yearsAtCompany: "6+ Years",
    achievements: ["Frontend Leadership", "UX Consistency"],
    quote: "User experience is built one interaction at a time.",
    createdAt: "2026-02-18T12:12:44.666Z",
    updatedAt: "2026-02-19T10:04:38.596Z",
    __v: 0,
  },
  {
    _id: "6995ac86f0671e2b2691a3a0",
    name: "Satishkumar",
    role: "Lead – Trex (Java)",
    image: "/images/sathish.png",
    //   "https://lnywvafdnrevojhgqfbt.supabase.co/storage/v1/object/public/mentors/1771416708411_sathish.png",
    shortStory: "Building strong and scalable backend systems.",
    fullStory:
      '      "Building strong backend systems has always been about clarity and discipline for me, and that’s exactly what my journey at CJSS Technologies has reinforced.\\n\\nWorking with Java-based systems and leading the Trex team has given me the opportunity to focus not just on development, but on how teams build, scale, and support reliable enterprise applications. From the beginning, the emphasis has been on clean design, maintainable code, and solutions that can grow with business needs.\\n\\nAs the team expanded, my role naturally moved into leadership. Handling the Trex Java team meant balancing hands-on technical work with mentoring, guiding design decisions, and supporting delivery across multiple projects. It also meant working closely with other teams to ensure backend services aligned well with overall system architecture.\\n\\nWhat I value most is the culture of collaboration. Discussions around design, performance, and best practices are encouraged, and teams are given the freedom to improve continuously. That environment helps developers grow in confidence while maintaining high technical standards.\\n\\nToday, I lead the Trex Java team at CJSS Technologies, overseeing development efforts that support the company’s services and client deliveries. My focus is on building strong teams, enabling consistent delivery, and ensuring that the systems we develop are reliable and scalable.\\n\\nCJSS Technologies has provided a space where technical leadership is valued and growth happens naturally through responsibility and trust. It’s a journey that continues to evolve, and one that I’m proud to be part of.",\r\n',
    yearsAtCompany: "5+ Years",
    achievements: ["Java Leadership", "Backend Architectur"],
    quote: '   "Strong foundations make scalable systems possible.",\r\n',
    createdAt: "2026-02-18T12:11:50.090Z",
    updatedAt: "2026-02-18T12:11:50.090Z",
    __v: 0,
  },
  {
    _id: "6995ac4bf0671e2b2691a39d",
    name: "Lekhya Pypuri",
    role: "Lead – Quality Assurance",
    image: "/images/lekhya.jpeg",
    //   "https://lnywvafdnrevojhgqfbt.supabase.co/storage/v1/object/public/mentors/1771416650753_lekhya.jpeg",
    shortStory: "Building trust through quality and discipline.",
    fullStory:
      "Quality has always been about more than testing for me — it’s about trust, consistency, and confidence in what we deliver. CJSS Technologies gave me the opportunity to build that mindset into the way teams work.\\n\\nOver time, my role evolved into leading the Quality Assurance function, where I work closely with testing teams, developers, and stakeholders to ensure quality is built into every stage of delivery. The focus isn’t just on finding defects, but on improving processes, strengthening test strategies, and enabling teams to deliver with confidence.\\n\\nWhat I value most here is collaboration. QA is involved early, not at the end. That approach helped us align better with development teams, improve test coverage, and reduce last-minute surprises. It also allowed the QA team to grow in skill and ownership.\\n\\nAs the organization scaled, so did the responsibility. Managing multiple projects, supporting enterprise clients, and maintaining consistent quality standards became a core part of my role. Leading the testing team means balancing detail with big-picture thinking — making sure quality never becomes an afterthought.\\n\\nToday, I lead the QA team at CJSS Technologies, overseeing testing efforts that support the company’s services and delivery commitments. I work closely with teams to ensure processes are clear, tools are effective, and quality remains a shared responsibility.\\n\\nCJSS Technologies has created an environment where QA is respected, voices are heard, and growth is continuous. Being part of this journey has been both challenging and rewarding — and it’s one I’m proud to be part of.",
    yearsAtCompany: "7+ Years",
    achievements: ["QA Leadership", "Process Excellence"],
    quote: "Quality is built through discipline and care.",
    createdAt: "2026-02-18T12:10:51.613Z",
    updatedAt: "2026-02-18T12:10:51.613Z",
    __v: 0,
  },
  {
    _id: "6995ac05f0671e2b2691a39a",
    name: "Saikiran Vemula",
    role: "Lead – TechOps",
    image: "/images/sai.png",
    //   "https://lnywvafdnrevojhgqfbt.supabase.co/storage/v1/object/public/mentors/1771416578863_sai.png",
    shortStory: "Driving operational excellence behind the scenes.",
    fullStory:
      '      "Keeping systems running smoothly is something I’ve always enjoyed, and CJSS Technologies gave me the space to turn that responsibility into impact.\\n\\nFrom the start, my focus has been on TechOps and operational excellence — making sure platforms, environments, and services work reliably for the teams that depend on them every day. The work isn’t always visible, but it’s critical. When systems are stable, teams can focus on building and delivering.\\n\\nWhat shaped my journey here is the level of ownership I was trusted with. Handling operations across projects meant understanding not just infrastructure, but also how development teams work, how deployments affect users, and how downtime impacts business. That pushed me to think beyond tasks and focus on reliability, performance, and continuous improvement.\\n\\nAs the company grew, the operational landscape became more complex. My role evolved into leading TechOps, supporting multiple teams and services, and ensuring that systems scale without compromising stability. Coordinating with developers, architects, and leadership became a key part of my work.\\n\\nToday, I lead the TechOps function at CJSS Technologies, handling operational services that support the entire organization. From environment management and deployments to monitoring and issue resolution, my responsibility is to ensure everything runs smoothly behind the scenes.\\n\\nWhat keeps this role interesting is the constant learning. Technology changes, systems grow, and expectations rise. CJSS Technologies provides an environment where operations are valued, collaboration is encouraged, and reliability is treated as a shared responsibility.\\n\\nBeing part of this journey has been rewarding, and it continues to challenge me in the best way.",\r\n',
    yearsAtCompany: "6+ Years",
    achievements: ["Operational Excellence", "Platform Reliability"],
    quote: "Operations excellence is invisible when done right.",
    createdAt: "2026-02-18T12:09:41.574Z",
    updatedAt: "2026-02-18T12:09:41.574Z",
    __v: 0,
  },
  {
    _id: "6995ab97f0671e2b2691a397",
    name: "Avinash",
    role: "Member – SAP CX",
    image: "/images/avinash.png",
    //   "https://lnywvafdnrevojhgqfbt.supabase.co/storage/v1/object/public/mentors/1771416468281_avinash.png",
    shortStory: "Growing through hands-on SAP Commerce experience.",
    fullStory:
      "Working with SAP Commerce (Hybris) at CJSS Technologies has been a steady journey of learning and growth.\\n\\nFrom the early days, I’ve been closely involved in building and enhancing customer experience solutions on SAP Commerce. The work here goes beyond implementation — it pushes you to understand how customer journeys, performance, and scalability come together in real enterprise platforms.\\n\\nOne thing that stands out to me at CJSS is the collaborative culture. Knowledge sharing is part of everyday work, whether it’s through design discussions, peer reviews, or problem-solving sessions within the team. That environment helped me strengthen my SAP CX foundation and gain confidence in handling complex requirements.\\n\\nAs my understanding of the platform grew, so did my responsibilities. I began contributing more actively to feature development, issue resolution, and overall experience improvements. Working closely with experienced leads helped me sharpen my technical thinking and approach challenges with a broader perspective.\\n\\nBeing part of projects for enterprise clients such as the Changi Group of Airports has been a valuable experience. It highlighted the importance of reliability, attention to detail, and delivering solutions that perform consistently at scale.\\n\\nToday, I am a member of the SAP CX team at CJSS Technologies, with solid hands-on knowledge of SAP Commerce and customer experience development. I continue to learn, collaborate, and contribute to building scalable commerce platforms alongside the team.\\n\\nCJSS Technologies has provided the right environment to grow steadily — through real projects, strong teamwork, and continuous learning. That’s what has made my journey here meaningful.",
    yearsAtCompany: "5+ Years",
    achievements: ["SAP CX Development", "Enterprise Platform Experience"],
    quote: "Growth comes from collaboration and real-world experience.",
    createdAt: "2026-02-18T12:07:51.084Z",
    updatedAt: "2026-02-18T12:07:51.084Z",
    __v: 0,
  },
  {
    _id: "6995ab4ff0671e2b2691a394",
    name: "Anjali Mohan",
    role: "Lead SAP Commerce (Hybris) Customer Experience",
    image: "/images/AnjaliMohan.png",
    //   "https://lnywvafdnrevojhgqfbt.supabase.co/storage/v1/object/public/mentors/1771416397491_AnjaliMohan.png",
    shortStory: "Leading scalable SAP Commerce customer experiences.",
    fullStory:
      '      "I joined CJSS Technologies four years ago, at a time when both the company and my role were evolving.\\n\\nFrom the beginning, I had the opportunity to work closely with SAP Commerce (Hybris) on real, live projects. What stood out to me was how quickly I was trusted with responsibility. I wasn’t just asked to deliver tasks — I was encouraged to understand the platform, the customer journeys, and the impact of what we were building.\\n\\nA lot of my learning came from everyday work. Design discussions, code reviews, and problem-solving sessions were constant, and I was always encouraged to ask questions and explore better approaches. That environment pushed me to think beyond implementation and focus on building scalable and reliable customer experience solutions.\\n\\nAs the projects grew, so did my role. I gradually moved into owning customer experience components, making technical decisions, and guiding delivery. Over time, my focus became firmly centered on SAP Hybris Customer Experience development, working across complex commerce flows and integrations.\\n\\nOne of the most meaningful parts of my journey has been contributing to enterprise platforms for clients like the Changi Group of Airports. Working at that scale brings a different level of responsibility — attention to detail, performance, and long-term stability really matter. Those experiences shaped how I approach both development and leadership.\\n\\nToday, I lead SAP Hybris Customer Experience initiatives at CJSS Technologies. I work closely with teams, mentor developers, and take ownership of quality and outcomes. The growth I’ve experienced here feels natural — driven by trust, learning, and consistent effort over time.\\n\\nCJSS Technologies has given me the space to grow, take ownership, and keep learning. It’s a journey that continues to challenge me, and one that I’m proud to be part of.",\r\n',
    yearsAtCompany: "5+ years",
    achievements: ["AP CX Leadership", "Enterprise CX Delivery"],
    quote: "Quality and consistency define long-term success.",
    createdAt: "2026-02-18T12:06:39.846Z",
    updatedAt: "2026-02-18T12:06:39.846Z",
    __v: 0,
  },
];
